language: ruby
cache: bundler
rvm: 2.5.0
bundler_args: "--without production development"
services: postgresql

env:
  - COMMAND="rspec"
  - COMMAND="rubocop -D -f simple"

matrix:
  allow_failures:
    - env: COMMAND="brakeman"

script:
  - "bundle exec $COMMAND"
